version: '3.8'
services:
  discord_bot:
    build: .
    container_name: discord_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # 将当前目录挂载到容器内，这样容器产生的 HTML 报表和 JSON 数据能直接写到宿主机上
      - ./:/app
    command: uv run python bot.py

  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uv run python tg_bot.py
